/**********
This library is free software; you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the
Free Software Foundation; either version 2.1 of the License, or (at your
option) any later version. (See <http://www.gnu.org/copyleft/lesser.html>.)

This library is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
more details.

You should have received a copy of the GNU Lesser General Public License
along with this library; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
**********/
// Copyright (c) 1996-2013, Live Networks, Inc.  All rights reserved
// A test program that demonstrates how to stream - via unicast RTP
// - various kinds of file on demand, using a built-in RTSP server.
// main program

/********************************************************************************************/
/*		Project	   	:	Jetson ORIN Camera/NVR			       */
/*		Author/Modified By 	:	Maheen Rasheed				       */
/*		Mediatronix Pvt Ltd,Pappanamcode,Industrial Estate,Trivandrum.	       */
/********************************************************************************************/
/********************************************************************************************/
/*                          Includes	                                                    */
/********************************************************************************************/
#ifndef _GNU_SOURCE
	#define _GNU_SOURCE
#endif

#include <pthread.h> 
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "liveMedia.hh"
#include "MtxH264VideoLiveServerMediaSubsession.hh"
#include "BasicUsageEnvironment.hh"
#include "GroupsockHelper.hh"
#include "MtxH264VideoLiveFramedSource.hh"
//#include "ADTSAudioLiveFramedSource.hh"

#include <arpa/inet.h>
#include <sys/socket.h>
#include <netdb.h>
#include <ifaddrs.h>
#include "../CameraServer/MtxSrc/Src/MediaServer/MtxStreamer/RTSPDefines.h"  

#include "version.h"

#define DEBUG 1

#if LIVEMEDIA_LIBRARY_VERSION_INT >= 1715731200
	#define LATEST_LIVE555 	1
#endif

// Fallback in case the Makefile define fails
#ifndef APP_VERSION
#define APP_VERSION "unknown"
#endif

#ifndef BUILD_TIMESTAMP
#define BUILD_TIMESTAMP "unknown"
#endif

#ifndef SZ_SM_BUFFER
#define SZ_SM_BUFFER	7
#endif

#ifndef SZ_BG_BUFFER
#define SZ_BG_BUFFER	4096
#endif


class HardenedRTSPServer: public RTSPServer 
{
public:
    static HardenedRTSPServer* createNew(UsageEnvironment& env, Port ourPort,
                                         UserAuthenticationDatabase* authDatabase,
                                         unsigned reclamationTestInterval = 65) {
        // We pass -1 for the sockets to tell Live555 to create them itself
        return new HardenedRTSPServer(env, -1, -1, ourPort, authDatabase, reclamationTestInterval);
    }

protected:
    // Notice the two 'int' parameters (socket4 and socket6) added here
    HardenedRTSPServer(UsageEnvironment& env, int socket4, int socket6, Port ourPort,
                       UserAuthenticationDatabase* authDatabase, unsigned reclamationTestInterval)
        : RTSPServer(env, socket4, socket6, ourPort, authDatabase, reclamationTestInterval) 
		{
			printf("H264 RTSP Server: %d\n", ntohs(ourPort.num()));
		}

    
	protected:
    HardenedRTSPServer(UsageEnvironment& env, Port ourPort, UserAuthenticationDatabase* authDatabase)
        : RTSPServer(env, 0, 0, ourPort, authDatabase, 65) {}

    // Overriding the URL generation to point back to the stunnel tunnel
private:
    char* rewriteToRTSPS(char* exp) const {
        if (!exp) return NULL;

        std::string url(exp);
        delete[] exp;

		// 2. Identify our ports
		portNumBits internalPort = ntohs(fServerPort.num());
		portNumBits stunnelPort = internalPort - 5;

		printf("fServerPort.num() : %d\n", ntohs(fServerPort.num()));
		printf("stunnelPort.num() : %d\n", stunnelPort);


		// 3. Determine if we should rewrite
		// We check if the 'url' generated by Live555 (based on the socket)
		// is already pointing to our internal port.
		std::string internalPortStr = ":" + std::to_string(internalPort);

		size_t portPos = url.find(internalPortStr);
       
        if (portPos != std::string::npos) 
		{
            // Change rtsp:// to rtsps://
            if (url.find("rtsp://") == 0) 
			{
                url.replace(0, 4, "rtsps");
            }

            //std::string stunnelPortStr = ":" + std::to_string(stunnelPort);
            //url.replace(portPos, internalPortStr.length(), stunnelPortStr);
        }

		printf("rewriteToRTSPS: Converted : %s\n", url.c_str());

        return strDup(url.c_str());
    }

};

void printSystemInfo() {
    std::cout << "Application Name: H264Streamer" << "\n";
    std::cout << "Application Version: " << APP_VERSION << "\n";
    std::cout << "Build TimeStamp: " << BUILD_TIMESTAMP << "\n";
    std::cout << "Live555 Version No.: " << LIVEMEDIA_LIBRARY_VERSION_INT << "\n";
    std::cout << "Live555 Version: " << LIVEMEDIA_LIBRARY_VERSION_STRING << "\n";
#ifdef LATEST_LIVE555
    std::cout << "We are on Modern LIVE55 > 1715731200" << "\n";
#endif
	
}


//VK


void* mtx_memcpy(void *dst, const void *src, size_t length);

void* mtx_memcpy(void *dst, const void *src, size_t length) 
{
	if (dst == NULL || src == NULL || length <= 0) 
	{
        return NULL;
    }
    
    return mempcpy(dst, src, length);
}

int32_t mtx_atoi(const char *str);

int32_t mtx_atoi(const char *str)
{
	char *endptr;
	long val;
	
	//reset errno
	errno = 0;
	val = strtol(str, &endptr, 10);
	
	// error conditions
	if (endptr == str || *endptr != '\0')
	{
		fprintf(stderr, "Error: Invalid input string %s\n", str);
		return (-1);
	}
	
	if ((errno == ERANGE && (val == LONG_MAX || val == LONG_MIN)) || val > INT_MAX || val < INT_MIN)
	{
		fprintf(stderr, "Error: Value out of range\n");
		return (-1);
	}
	
	//success
	return (int32_t)val;
}

void mtx_strlen(const char *s);

void mtx_strlen(const char *s)
{

}

void mtx_strncpy(char *destination, const char *src, size_t len, size_t dest_size);

void mtx_strncpy(char *destination, const char *src, size_t len, size_t dest_size)
{
	if( len >= dest_size)
		len = (dest_size - 1);

	snprintf(destination, len+1, "%s", src);
}

void mtx_strcpy(char *destination, const char *src);

void mtx_strcpy(char *destination, const char *src)
{
	size_t len = strnlen(src,1024);

	snprintf(destination, len+1, "%s", src);
}

//LIVE555 Latest Compatibility
//Ashutosh

#include <errno.h>
#include <climits>

/**
 * Maps a sockaddr_in (IPv4) to a sockaddr_storage (Generic)
 * @param src: Pointer to the existing IPv4 address structure
 * @param dst: Pointer to the storage structure to be populated
 */
void fill_sockaddr_storage(struct sockaddr_in const* src, struct sockaddr_storage* dst) {
    if (src == nullptr || dst == nullptr) return;

    // 1. Clear the destination to prevent garbage data
    memset(dst, 0, sizeof(struct sockaddr_storage));

    // 2. Copy the IPv4 structure into the storage
    // sockaddr_storage is guaranteed to be large enough to hold sockaddr_in
    mtx_memcpy(dst, src, sizeof(struct sockaddr_in));

    // 3. Explicitly set the family (though usually covers this)
    dst->ss_family = AF_INET;
}

/**
 * Converts a raw in_addr to the modern sockaddr_storage format
 * @param src_old: The legacy IPv4 address struct
 * @param port: The Port object (Live555 type)
 * @param dst: The destination storage struct
 */
void convert_to_storage(struct in_addr const& src_old, Port port, struct sockaddr_storage& dst) {
    // 1. Wipe the destination to ensure no "ghost" data exists
    memset(&dst, 0, sizeof(struct sockaddr_storage));

    // 2. Treat the storage as an IPv4 structure for easy assignment
    struct sockaddr_in* ipv4 = (struct sockaddr_in*)&dst;

    // 3. Populate the necessary fields
    ipv4->sin_family = AF_INET;
    ipv4->sin_addr = src_old;
    ipv4->sin_port = htons(port.num()); // Live555 Port.num() is usually in host order
}
//End of LIVE555 Latest Compatibility

/********************************************************************************************/
/*                          Extern Variables                                      */
/********************************************************************************************/
#ifdef LATEST_LIVE555

double Live555H264FrameRate = 10.0;
#else
extern double Live555H264FrameRate;

#endif

//extern unsigned char fFrameRate;
extern SHM_RTSP_SERVER *H264ShmImgPtr;
/********************************************************************************************/
/*                          Extern Function Prototypes                                      */
/********************************************************************************************/
extern void ConfigureRTSPServerSharedMemory(void);
extern void ConfigureX264ServerSharedMemory(void);
/********************************************************************************************/
/*                          Global Variable	                                            */
/********************************************************************************************/
//char RtspUserName[2][9];
//char RtspUserPassword[2][7];

UsageEnvironment* env;

//For Multicast Streaming of ENCV
RTPSink* videoSink;
H264VideoStreamFramer* mtxSource;
FramedSource* mimgSource;

//For Multicast Streaming of ADTS
RTPSink* audioSink;
//ADTSAudioLiveFramedSource* audioSource;

// To make the second and subsequent client for each stream reuse the same
// input stream as the first client (rather than playing the file from the
// start for each client), change the following "False" to "True":
Boolean reuseFirstSource = True;//False;

// To stream *only* MPEG-1 or 2 video "I" frames
// (e.g., to reduce network bandwidth),
// change the following "False" to "True":
Boolean iFramesOnly = False;

//To Select Multicast or Unicast Streaming
Boolean isMultiCast = False;

Boolean isAudio = False;
char streamName[64];

char hostaddress[NI_MAXHOST];
/********************************************************************************************/
/*                          Function Prototypes                                             */
/********************************************************************************************/
//To Start Multicast Streaming
void play(char const* inputFileName); // forward
static void announceStream(RTSPServer* rtspServer, ServerMediaSession* sms,char const* streamName, char const* inputFileName);// fwd
/********************************************************************************************/
/*                          Function Definition                                             */
/********************************************************************************************/
void getip(void)
{
    struct ifaddrs *ifaddr, *ifa;
    int s;
    

    if (getifaddrs(&ifaddr) == -1) 
    {
        perror("getifaddrs");
        exit(EXIT_FAILURE);
    }


    for (ifa = ifaddr; ifa != NULL; ifa = ifa->ifa_next) 
    {
        if (ifa->ifa_addr == NULL)
            continue;  

        s=getnameinfo(ifa->ifa_addr,sizeof(struct sockaddr_in),hostaddress, NI_MAXHOST, NULL, 0, NI_NUMERICHOST);

        if((strcmp(ifa->ifa_name,"enP8p1s0")==0)&&(ifa->ifa_addr->sa_family==AF_INET))
        {
            if (s != 0)
            {
                printf("getnameinfo() failed: %s\n", gai_strerror(s));
                exit(EXIT_FAILURE);
            }
            //printf("\tInterface : <%s>\n",ifa->ifa_name );
            //printf("\t  Address : <%s>\n", host); 
	    break;
        }
    }
    freeifaddrs(ifaddr);
}

int main(int argc, char** argv) 
{
	//int i=0;
	unsigned char pwdbuffer[SZ_SM_BUFFER]={0};
	//char onvifcmdbuff[SZ_BG_BUFFER]={0};
	//char ddcmdbuff[SZ_BG_BUFFER]={0};

	bool debug_mode = false;
	bool http_tunnelling = false;

	int width,height;
	
	if (argc >= 2)
	{
		if(strcmp(argv[1], "--version") == 0)
		{
			printf("H264RTSP %s", APP_VERSION);
		}
		else if(strcmp(argv[1], "-v") == 0)
		{
			printf("-----------------------\n Version Details\n-----------------------\n");
			printSystemInfo();
		}
		else if(strcmp(argv[1], "-d") == 0)
		{
			debug_mode = true;
			printf("-----------------------\n Debug Mode \n-----------------------\n");
		}
		else if(strcmp(argv[1], "-h") == 0)
		{
			printf("-----------------------\n Help Summary\n-----------------------\n");
			printSystemInfo();
			printf("Valid argument List:\n");
			printf("\t1. Display Version Details: -v\n");
			printf("\t2. Enable Optional HTTP Tunneling: -u\n");
			printf("\t3. Display Help Summary: -h\n");
		}
		else if(strcmp(argv[1], "-u") == 0)
		{
			http_tunnelling = true;
		}
		else
		{
			printf("Error: Invalid Arguments");
			printf("Valid argument List:\n");
			printf("\t1. Display Version Details: -v\n");
			printf("\t2. Enable Optional HTTP Tunneling: -u\n");
			printf("\t3. Display Help Summary: -h\n");
		}
		if( debug_mode == false && http_tunnelling == false )
			exit(0);
	}

	printSystemInfo();
	
	ConfigureRTSPServerSharedMemory(); 
	ConfigureX264ServerSharedMemory();
	sleep(10);	
	
	getip();
	if(H264ShmImgPtr->rtsp_config_details.resolution==THREE_MP) 
	{
		width=1280;
		height=720;
	}
	if(H264ShmImgPtr->rtsp_config_details.resolution==FIVE_MP) 
	{
		width=1280;
		height=1024;
	}
	if(H264ShmImgPtr->rtsp_config_details.resolution==EIGHT_MP) 
	{
		//width=1920;
		//height=1080;
		width=1280;
		height=720;
	}
	Live555H264FrameRate=10.0;

	printf("H264 Resolution Dimensions: %d X %d\n", width, height);

	if(debug_mode == true)
	{
		printf("H264 Resolution Type: %d\nFrameRate: %g\n", 
				H264ShmImgPtr->rtsp_config_details.resolution,
				Live555H264FrameRate);

		printf("Model Name: %s\n", H264ShmImgPtr->rtsp_config_details.model_name);
		printf("Host Address: %s\n", hostaddress);
		printf("Manufacturer: %s\n", H264ShmImgPtr->rtsp_config_details.manufacturer);
	}

	
	mtx_strncpy((char*)pwdbuffer,(char*)&H264ShmImgPtr->rtsp_config_details.remote_user_password[0][0],6, SZ_SM_BUFFER);
	
	//onvif and wsdd is already running in jpeg rtsp.
	#if 0 	
	mtx_sprintf(onvifcmdbuff,"./onvif_srvd  --ifs eth0 --scope ""onvif://www.onvif.org/name/MtxCam"" \
			      --scope ""onvif://www.onvif.org/Profile/S"" --name RTSP --width %d --height %d --url rtsp://%s:%d/%s --type JPEG --user %s --password %s --model %s\
				 --hardware_id %s --serial_num %s --firmware_ver %s --manufacturer %s",
				width,height,(unsigned char*)hostaddress,
				mtx_atoi((char*)H264ShmImgPtr->rtsp_config_details.rtsp_portnum),(const char*)H264ShmImgPtr->rtsp_config_details.rtsp_stream_name,
				(char*)&H264ShmImgPtr->rtsp_config_details.remote_user_name[0][0],(char*)pwdbuffer,
				(char*)H264ShmImgPtr->rtsp_config_details.model_name,
				(char*)H264ShmImgPtr->rtsp_config_details.hardware_ID,
				(char*)H264ShmImgPtr->rtsp_config_details.serial_no,
				(char*)H264ShmImgPtr->rtsp_config_details.firmware_version,
				(char*)H264ShmImgPtr->rtsp_config_details.manufacturer);

	mtx_sprintf(ddcmdbuff,"./wsdd  --if_name eth0 --xaddr http://%s:%d/onvif/device_service --type tdn:NetworkVideoTransmitter \
				--scope ""onvif://www.onvif.org/name/MtxCam"" --scope ""onvif://www.onvif.org/Profile/S""",
				(unsigned char*)hostaddress,mtx_atoi((char*)H264ShmImgPtr->rtsp_config_details.onvif_portnum));
	#endif
	
	// Begin by setting up our usage environment:
	TaskScheduler* scheduler = BasicTaskScheduler::createNew();
	env = BasicUsageEnvironment::createNew(*scheduler);

	UserAuthenticationDatabase* authDB = NULL;
	//printf("\nmtx %s %s %s %s \n",(char*)RtspUserName[0],(char*)RtspUserName[1],(char*)RtspUserPassword[0],(char*)RtspUserPassword[1]);
	//printf("\nKKKK %s %s %s %s \n",SystemVariablesShmPTR->RtspUserName[0],
	//SystemVariablesShmPTR->RtspUserName[1],SystemVariablesShmPTR->RtspUserPassword[0],SystemVariablesShmPTR->RtspUserPassword[1]);
//#ifdef ACCESS_CONTROL
#if 0
	// To implement client access control to the RTSP server, do the following:
	authDB = new UserAuthenticationDatabase;
	//authDB->addUserRecord("ADMIN-01","111111"); // replace these with real strings
	authDB->addUserRecord(SystemVariablesShmPTR->RtspUserName[0],SystemVariablesShmPTR->RtspUserPassword[0]); // replace these with real strings
	authDB->addUserRecord(SystemVariablesShmPTR->RtspUserName[1],SystemVariablesShmPTR->RtspUserPassword[1]); // replace these with real strings
	// Repeat the above with each <username>, <password> that you wish to allow
	// access to the server.  
#endif

	if(H264ShmImgPtr->rtsp_config_details.rtsp_authentication==TRUE)
	{
		// To implement client access control to the RTSP server, do the following:
		authDB = new UserAuthenticationDatabase;
		//authDB->addUserRecord("ADMIN-01","111111"); // replace these with real strings
		mtx_strncpy((char*)pwdbuffer,(char*)&H264ShmImgPtr->rtsp_config_details.remote_user_password[0][0],6, SZ_SM_BUFFER);
		authDB->addUserRecord((char*)&H264ShmImgPtr->rtsp_config_details.remote_user_name[0][0],(char*)pwdbuffer); // replace these with real strings
		mtx_strncpy((char*)pwdbuffer,(char*)&H264ShmImgPtr->rtsp_config_details.remote_user_password[1][0],6, SZ_SM_BUFFER);
		authDB->addUserRecord((char*)&H264ShmImgPtr->rtsp_config_details.remote_user_name[1][0],(char*)pwdbuffer); // replace these with real strings

		// Repeat the above with each <username>, <password> that you wish to allow
		// access to the server.  
	}

	struct in_addr destinationAddress;
	const unsigned char ttl = 255;  
	const unsigned maxCNAMElen = 100;
	unsigned char CNAME[maxCNAMElen+1];

	Groupsock* rtpGroupsock;
	Groupsock* rtcpGroupsock;
	//Groupsock* rtpGroupsockAudio;
	//Groupsock* rtcpGroupsockAudio;

	//RTCPInstance* audioRTCP = NULL;

	const unsigned short rtpPortNumAudio =6668;  
	const unsigned short rtcpPortNumAudio = 6669;  
	const Port rtpPortAudio(rtpPortNumAudio);
	const Port rtcpPortAudio(rtcpPortNumAudio);  
	const unsigned short rtpPortNum = 18886;
	const unsigned short rtcpPortNum = 18887;

	const Port rtpPort(rtpPortNum);
	const Port rtcpPort(rtcpPortNum);


	RTCPInstance* rtcp=NULL;

	//printf(">>>>>>> %d %d %d %d %d\n",rtpPortNumAudio,rtcpPortNumAudio,rtpPortNum,rtcpPortNum,isMultiCast);

	//const unsigned estimatedSessionBandwidthAudio = 160; // in kbps; for RTCP b/w share
	const unsigned estimatedSessionBandwidth = 500; // in kbps; for RTCP b/w share

	//used in H264or5VideoStreamFramer.cpp
	//Live555H264FrameRate=8; //fps
	//fFrameRate=8;
  
	#if 1
	if(isMultiCast)
	{    
		// Create 'groupsocks' for RTP and RTCP:
		destinationAddress.s_addr = chooseRandomIPv4SSMAddress(*env);
		// Note: This is a multicast address.  If you wish instead to stream
		// using unicast, then you should use the "testOnDemandRTSPServer"
		// test program - not this test program - as a model.

		gethostname((char*)CNAME, maxCNAMElen);
		CNAME[maxCNAMElen] = '\0'; // just in case  

		#if 0 
		//audio    
		if(isAudio)
		{
			audioSource = ADTSAudioLiveFramedSource::createNew(*env,g_media_cfg.inputFileName); 
			rtpGroupsockAudio = new Groupsock(*env, destinationAddress, rtpPortAudio, ttl);
			rtpGroupsockAudio->multicastSendOnly(); // because we're a SSM source
			// Create an 'ADTS Audio RTP' sink from the RTP 'groupsock':
			audioSink = MPEG4GenericRTPSink::createNew(*env, rtpGroupsockAudio,96,audioSource->samplingFrequency(),"audio", "AAC-hbr", audioSource->configStr(),audioSource->numChannels());
				      
			// set the RTP timestamp frequency 'for real' later
			// Create (and start) a 'RTCP instance' for this RTP sink:
			rtcpGroupsockAudio = new Groupsock(*env, destinationAddress, rtcpPortAudio, ttl);
			rtcpGroupsockAudio->multicastSendOnly(); // because we're a SSM source
			//const unsigned estimatedSessionBandwidthAudio = 160; // in kbps; for RTCP b/w share
			//audioRTCP = RTCPInstance::createNew(*env, rtcpGroupsockAudio,estimatedSessionBandwidthAudio,CNAME,audioSink,NULL /* we're a server */,True /* we're a SSM source */);// Note: This starts RTCP running automatically	
			audioRTCP = RTCPInstance::createNew(*env, rtcpGroupsockAudio,estimatedSessionBandwidthAudio,CNAME,audioSink,NULL,True);
		}
		///////////audio ends here
		#endif

#ifdef LATEST_LIVE555
		struct sockaddr_storage NewRtpPortDestinationAddress;
		convert_to_storage(destinationAddress, rtpPort, NewRtpPortDestinationAddress);

		struct sockaddr_storage NewRtcpPortDestinationAddress;
		convert_to_storage(destinationAddress, rtcpPort, NewRtcpPortDestinationAddress);

 
		rtpGroupsock= new Groupsock(*env, NewRtpPortDestinationAddress, rtpPort, ttl);
		rtpGroupsock->multicastSendOnly(); // we're a SSM source
 
		rtcpGroupsock=new Groupsock(*env, NewRtcpPortDestinationAddress, rtcpPort, ttl);
		rtcpGroupsock->multicastSendOnly(); // we're a SSM source

#else
		


		//video
		//Groupsock rtpGroupsock(*env, destinationAddress, rtpPort, ttl);
		rtpGroupsock= new Groupsock(*env, destinationAddress, rtpPort, ttl);
		rtpGroupsock->multicastSendOnly(); // we're a SSM source
		//Groupsock rtcpGroupsock(*env, destinationAddress, rtcpPort, ttl);
		rtcpGroupsock=new Groupsock(*env, destinationAddress, rtcpPort, ttl);
		rtcpGroupsock->multicastSendOnly(); // we're a SSM source
#endif
		// Create a 'H264 Video RTP' sink from the RTP 'groupsock':
		OutPacketBuffer::maxSize = 100000;

		videoSink = H264VideoRTPSink::createNew(*env,rtpGroupsock, 96);

		// Create (and start) a 'RTCP instance' for this RTP sink:
		rtcp  = RTCPInstance::createNew(*env,rtcpGroupsock,estimatedSessionBandwidth, CNAME,videoSink,NULL,True);
		///////////video ends here
	}
	#endif

	// Begin by setting up our usage environment:
	// Create the RTSP server:
	int rtsp_listen_port = mtx_atoi((char*)H264ShmImgPtr->rtsp_config_details.rtsp_portnum);
	OutPacketBuffer::maxSize = 600000;

#ifdef HARDENNED_RTSPSERVER
	HardenedRTSPServer* rtspServer=NULL;
	rtspServer = HardenedRTSPServer::createNew(*env, rtsp_listen_port, authDB, 65); 	
#else	
	RTSPServer* rtspServer=NULL;
	rtspServer = RTSPServer::createNew(*env, rtsp_listen_port, authDB, 65); 
#endif

	if (rtspServer == NULL) 
	{
		*env << "Failed to create RTSP server: " << env->getResultMsg() << "\n";
		exit(1);
	}

	char const* descriptionString = "Session streamed by \"H264CameraRTSPServer\"";

	// Set up each of the possible streams that can be served by the
	// RTSP server.  Each such stream is implemented using a
	// "ServerMediaSession" object, plus one or more
	// "ServerMediaSubsession" objects for each audio/video substream.

	mtx_strcpy(streamName, (const char*)H264ShmImgPtr->rtsp_config_details.rtsp_stream_name);

	ServerMediaSession* sms = ServerMediaSession::createNew(*env, streamName, streamName,descriptionString,True /*SSM*/);

	//for single audio(aac) rtsp streaming testing
	//aac adts
	#if 0   
	//Audio
	if(isMultiCast)
	{
		sms->addSubsession(PassiveServerMediaSubsession::createNew(*audioSink, audioRTCP));
	}
	else
	{
		sms->addSubsession(ADTSAudioLiveServerMediaSubsession::createNew(*env, g_media_cfg.inputFileName, reuseFirstSource));
	}
	#endif
	
	if(isMultiCast)
	{
		sms->addSubsession(PassiveServerMediaSubsession::createNew(*videoSink, rtcp));
	}
	else
	{
		sms->addSubsession(MtxH264VideoLiveServerMediaSubsession::createNew(*env, "sample_h264.clip", reuseFirstSource));
	}

	rtspServer->addServerMediaSession(sms);
	announceStream(rtspServer, sms, streamName, streamName);
  

	//onvif and wsdd is already running in jpeg rtsp.
	#if 0
	int nRet;	
	nRet=systemnotused(onvifcmdbuff);
	if(nRet<0)
	{
		printfnotused("onvifcmdbuff failed\n");
	}	
	sleep(1);
	nRet=systemnotused(ddcmdbuff);
	if(nRet<0)
	{
		printfnotused("ddcmdbuff failed\n");
	}	
	sleep(1);
	#endif
	
	// Also, attempt to create a HTTP server for RTSP-over-HTTP tunneling.
	// Try first with the default HTTP port (80), and then with the alternative HTTP
	// port numbers (8000 and 8080).

	if(isMultiCast)
	{
		//play(streamName);
	}
	else
	{
		if(http_tunnelling == true)
		{
			if (rtspServer->setUpTunnelingOverHTTP(81) || rtspServer->setUpTunnelingOverHTTP(8001) || rtspServer->setUpTunnelingOverHTTP(8081)) 
			{
				*env << "\n(We use port " << rtspServer->httpServerPortNum() << " for optional RTSP-over-HTTP tunneling.)\n";
			} 
			else 
			{
				*env << "\n(RTSP-over-HTTP tunneling is not available.)\n";
			}
		}
	} 

	env->taskScheduler().doEventLoop(); // does not return

	return 0; // only to prevent compiler warning
}

static void announceStream(RTSPServer* rtspServer, ServerMediaSession* sms,char const* streamName, char const* inputFileName) 
{
	char* url = rtspServer->rtspURL(sms);

	UsageEnvironment& env = rtspServer->envir();

	env << "\n\"" << streamName << "\" stream, from the file \""
	<< inputFileName << "\"\n";
	env << "Play this stream using the URL \"" << url << "\"\n";

	delete[] url;
}

void afterPlaying(void* /*clientData*/) 
{
	*env << "...done reading from file\n";

	#if 0
	if (audioSink != NULL) 
	{
	audioSink->stopPlaying();
	}
	Medium::close(audioSource);
	#endif  

	if (videoSink != NULL) 
	{
		videoSink->stopPlaying();
	}

	Medium::close(mtxSource);
	// Note that this also closes the input file that this source read from.

	// Start playing once again:
	play(streamName);
}

void play(char const* inputFileName) 
{
	MtxH264VideoLiveFramedSource* liveSource = MtxH264VideoLiveFramedSource::createNew(*env, inputFileName);

	if (liveSource == NULL) 
	{
		*env << "Unable to open file \"" << inputFileName
		<< "\" as a byte-stream file source\n";
		exit(1);
	}

	FramedSource* videoES = liveSource;

	// Create a framer for the Video Elementary Stream:
	mtxSource = H264VideoStreamFramer::createNew(*env, videoES);

	// Finally, start playing:
	*env << "Beginning to read from h264 encoder...\n";
	videoSink->startPlaying(*mtxSource, afterPlaying, videoSink);

	#if 0  
	if(audioSink != NULL)
	{
		// Finally, start playing:
		*env << "Beginning to read from audio encoder...\n";
		audioSink->setRTPTimestampFrequency(audioSource->samplingFrequency());
		audioSink->startPlaying(*audioSource, afterPlaying, audioSink);
	}
	#endif
}

